print("Enter your first name: ")
fname = input()
print("Enter your last name: ")
lname = input()
print("Enter your middle name: ")
mname = input()
print("When is your birthday? ")
birthday = input()
print("Gender? ")
gender = input()
print("Where do you live? ")
address = input()
print("Course?")
course = input()
print("Year level?")
yearlvl = input()
print(sep="\n")
print("Student Information")
print("Name:", fname, mname, lname)
print("Birthday:", birthday)
print("Gender:", gender)
print("Address:", address)
print("Course:", course)
print("Year level:", yearlvl, "year")